### ISSUE TITLE
report says LME not supported

### ISSUE THREAD

**Issue by mamscience** [easystats/report#109]
Hi

I provided a model made by nlme [lme()], but report doesn't want it. (see reprex). I think I'm missing something, as the documentation mentions that it is suppored... The error it throws says:

```
Error in report.default(reprexmodel) : 
  The input you provided is not supported yet by report :(

```
```
library(magrittr)
library(nlme)
library(report)
reprex <- data.frame(time = as.factor(c(1,2,3,4,5, 1, 2,3,4,5, 1, 2,3,4,5, 1, 2,3,4,5, 1, 2,3,4,5, 1, 2,3,4,5)), group=c(1,1,1,1,1, 2,2,2,2,2,1,1,1,1,1, 2,2,2,2,2,1,1,1,1,1, 2,2,2,2,2), id=c(10,10,10,10,10,15,15,15,15,15,20,20,20,20,20,25,25,25,25,25,30,30,30,30,30, 35,35,35,35,35), sum=c(0,5,10,15,20, 0,20,25,45,50,0,5,10,15,20, 0,20,25,45,50,0,5,10,15,20, 0,20,25,45,50))

reprexmodel <-  lme(log(sum+1)  ~ as.numeric(time) * group,        
                    random  = ~ 1|id,
                    correlation = corAR1(form =~  as.numeric(time)| id), 
                    data=reprex, na.action = na.exclude)
report(reprexmodel)
```

I updated everything to the latest version. My sessions info:
```

R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  splines   stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] report_0.2.0       parameters_0.9.0.1 sjPlot_2.8.6       mgcv_1.8-33        aomisc_0.64       
 [6] multcompView_0.1-8 car_3.0-10         carData_3.0-4      plyr_1.8.6         drc_3.0-1         
[11] MASS_7.3-53        influence.ME_0.9-9 mice_3.11.0        ggsignif_0.6.0     broom.mixed_0.2.6 
[16] rcompanion_2.3.25  data.table_1.13.2  emmeans_1.5.2-1    predictmeans_1.0.4 lme4_1.1-25       
[21] Matrix_1.2-18      gtsummary_1.3.5    stargazer_5.2.2    survminer_0.4.8    coin_1.3-1        
[26] finalfit_1.0.2     rstatix_0.6.0      ggfortify_0.4.11   table1_1.2         knitr_1.30        
[31] MuMIn_1.43.17      geepack_1.3-1      Hmisc_4.4-1        Formula_1.2-4      survival_3.2-7    
[36] lattice_0.20-41    svglite_1.2.3.2    tableone_0.12.0    reshape2_1.4.4     readxl_1.3.1      
[41] ggpubr_0.4.0       forcats_0.5.0      stringr_1.4.0      purrr_0.3.4        readr_1.4.0       
[46] tidyr_1.1.2        tibble_3.0.4       ggplot2_3.3.2      tidyverse_1.3.0    dplyr_1.0.2       
[51] haven_2.3.1        FSA_0.8.30         doBy_4.6.7         nlme_3.1-149       magrittr_1.5      
[56] ggeffects_0.16.0.1

loaded via a namespace (and not attached):
  [1] tidyselect_1.1.0     htmlwidgets_1.5.2    grid_4.0.3           devtools_2.3.2      
  [5] munsell_0.5.0        codetools_0.2-16     effectsize_0.4.0.001 statmod_1.4.35      
  [9] withr_2.3.0          colorspace_1.4-1     rstudioapi_0.11      stats4_4.0.3        
 [13] DescTools_0.99.38    labeling_0.4.2       KMsurv_0.1-5         farver_2.0.3        
 [17] rprojroot_1.3-2      coda_0.19-4          vctrs_0.3.4          generics_0.0.2      
 [21] TH.data_1.0-10       xfun_0.18            easystats_0.2.0      R6_2.5.0            
 [25] assertthat_0.2.1     scales_1.1.1         multcomp_1.4-14      nnet_7.3-14         
 [29] rootSolve_1.8.2.1    gtable_0.3.0         processx_3.4.4       lmom_2.8            
 [33] sandwich_3.0-0       rlang_0.4.8          EMT_1.1              systemfonts_0.3.2   
 [37] TMB_1.7.18           broom_0.7.2          GLMMadaptive_0.7-15  checkmate_2.0.0     
 [41] yaml_2.2.1           abind_1.4-5          modelr_0.1.8         backports_1.1.10    
 [45] usethis_1.6.3        tools_4.0.3          ellipsis_0.3.1       RColorBrewer_1.1-2  
 [49] sessioninfo_1.1.1    ggridges_0.5.2       Rcpp_1.0.5           base64enc_0.1-3     
 [53] prettyunits_1.1.1    ps_1.4.0             rpart_4.1-15         zoo_1.8-8           
 [57] cluster_2.1.0        fs_1.5.0             survey_4.0           tinytex_0.26        
 [61] openxlsx_4.2.3       lmtest_0.9-38        reprex_0.3.0         effects_4.2-0       
 [65] mvtnorm_1.1-1        sjmisc_2.8.5         matrixStats_0.57.0   pkgload_1.1.0       
 [69] hms_0.5.3            evaluate_0.14        xtable_1.8-4         pbkrtest_0.4-8.6    
 [73] sjstats_0.18.0       rio_0.5.16           jpeg_0.1-8.1         gridExtra_2.3       
 [77] testthat_2.3.2       compiler_4.0.3       crayon_1.3.4         minqa_1.2.4         
 [81] htmltools_0.5.0      libcoin_1.0-6        expm_0.999-5         Exact_2.1           
 [85] lubridate_1.7.9      DBI_1.1.0            sjlabelled_1.1.7     dbplyr_1.4.4        
 [89] see_0.6.0.1          boot_1.3-25          cli_2.1.0            mitools_2.4         
 [93] DHARMa_0.3.3.0       insight_0.10.0.1     pkgconfig_2.0.3      km.ci_0.5-2         
 [97] numDeriv_2016.8-1.1  foreign_0.8-80       xml2_1.3.2           foreach_1.5.1       
[101] estimability_1.3     rvest_0.3.6          callr_3.5.1          digest_0.6.27       
[105] rmarkdown_2.5        cellranger_1.1.0     survMisc_0.5.5       htmlTable_2.1.0     
[109] Deriv_4.1.1          nortest_1.0-4        gld_2.6.2            gdtools_0.2.2       
[113] curl_4.3             gtools_3.8.2         modeltools_0.2-23    nloptr_1.2.2.2      
[117] lifecycle_0.2.0      jsonlite_1.7.1       desc_1.2.0           fansi_0.4.1         
[121] pillar_1.4.6         plotrix_3.7-8        pkgbuild_1.1.0       httr_1.4.2          
[125] remotes_2.2.0        glue_1.4.2           bayestestR_0.7.5.1   zip_2.1.1           
[129] png_0.1-7            iterators_1.0.13     performance_0.5.1    class_7.3-17        
[133] stringi_1.5.3        blob_1.2.1           memoise_1.1.0        latticeExtra_0.6-29 
[137] e1071_1.7-4    
```

**Comment by strengejacke** [comment]
After updating insight, parameters and report from GitHub, it should work now. However, the output still yields a lot of warnings, that maybe can be suppressed. @DominiqueMakowski can you look at it and figure out where warnings come from?

**Comment by strengejacke** [comment]
@DominiqueMakowski These mainly come from refitting the model inside _effectsize_, so the last commit should resolve this issue as well.

**Comment by strengejacke** [comment]
I _think_ this can be closed.

**Comment by mamscience** [comment]
Hi all

Thanks for your quick commit. Unfortunately it still throws errors and no report. The reprex gives this as an output:

```
Error in MEEM(object, conLin, control$niterEM) : 
  NA/NaN/Inf in foreign function call (arg 1)
```


And my own model throws a different error:

```
Error in lme.formula(fixed = log(mme.sum + 1) ~ ns(as.numeric(mme.postopday,  : 
  nlminb problem, convergence error code = 1
  message = iteration limit reached without convergence (10)
In addition: Warning message:
In insight::format_value(order, digits = 0, ...) :
  NAs introduced by coercion
```

**Comment by strengejacke** [comment]
Have you updated the packages _insight_, _parameters_ and _report_ from GitHub?

**Comment by mamscience** [comment]
Yes I have. So, I also restarted Rstudio couple of times. Here's my sessions info:
`R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] splines   parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] magrittr_1.5       knitr_1.30         MuMIn_1.43.17      geepack_1.3-1      Hmisc_4.4-1        Formula_1.2-4      survival_3.2-7    
 [8] lattice_0.20-41    svglite_1.2.3.2    tableone_0.12.0    reshape2_1.4.4     readxl_1.3.1       ggpubr_0.4.0       forcats_0.5.0     
[15] stringr_1.4.0      purrr_0.3.4        readr_1.4.0        tidyr_1.1.2        tibble_3.0.4       ggplot2_3.3.2      tidyverse_1.3.0   
[22] dplyr_1.0.2        haven_2.3.1        doBy_4.6.7         report_0.2.0       rcompanion_2.3.25  ggeffects_0.16.0.1 data.table_1.13.2 
[29] emmeans_1.5.2-1    predictmeans_1.0.4 nlme_3.1-149       lme4_1.1-25        Matrix_1.2-18     

loaded via a namespace (and not attached):
  [1] backports_1.1.10     systemfonts_0.3.2    plyr_1.8.6           TMB_1.7.18           TH.data_1.0-10       digest_0.6.27       
  [7] foreach_1.5.1        htmltools_0.5.0      fansi_0.4.1          checkmate_2.0.0      DHARMa_0.3.3.0       cluster_2.1.0       
 [13] openxlsx_4.2.3       modelr_0.1.8         matrixStats_0.57.0   sandwich_3.0-0       jpeg_0.1-8.1         colorspace_1.4-1    
 [19] blob_1.2.1           rvest_0.3.6          mitools_2.4          xfun_0.18            crayon_1.3.4         jsonlite_1.7.1      
 [25] libcoin_1.0-6        Exact_2.1            zoo_1.8-8            iterators_1.0.13     glue_1.4.2           gtable_0.3.0        
 [31] GLMMadaptive_0.7-15  car_3.0-10           abind_1.4-5          scales_1.1.1         mvtnorm_1.1-1        DBI_1.1.0           
 [37] rstatix_0.6.0        Rcpp_1.0.5           performance_0.5.1    htmlTable_2.1.0      xtable_1.8-4         foreign_0.8-80      
 [43] stats4_4.0.3         survey_4.0           htmlwidgets_1.5.2    httr_1.4.2           RColorBrewer_1.1-2   modeltools_0.2-23   
 [49] ellipsis_0.3.1       pkgconfig_2.0.3      nnet_7.3-14          multcompView_0.1-8   dbplyr_1.4.4         tidyselect_1.1.0    
 [55] rlang_0.4.8          effectsize_0.4.0.001 munsell_0.5.0        cellranger_1.1.0     tools_4.0.3          cli_2.1.0           
 [61] generics_0.0.2       sjlabelled_1.1.7     broom_0.7.2          evaluate_0.14        EMT_1.1              yaml_2.2.1          
 [67] fs_1.5.0             zip_2.1.1            coin_1.3-1           rootSolve_1.8.2.1    xml2_1.3.2           compiler_4.0.3      
 [73] pbkrtest_0.4-8.6     rstudioapi_0.11      png_0.1-7            curl_4.3             e1071_1.7-4          ggsignif_0.6.0      
 [79] reprex_0.3.0         statmod_1.4.35       DescTools_0.99.38    stringi_1.5.3        parameters_0.9.0.1   gdtools_0.2.2       
 [85] nloptr_1.2.2.2       vctrs_0.3.4          effects_4.2-0        pillar_1.4.6         lifecycle_0.2.0      lmtest_0.9-38       
 [91] estimability_1.3     insight_0.10.0.1     lmom_2.8             latticeExtra_0.6-29  R6_2.5.0             gridExtra_2.3       
 [97] rio_0.5.16           gld_2.6.2            codetools_0.2-16     boot_1.3-25          MASS_7.3-53          assertthat_0.2.1    
[103] withr_2.3.0          nortest_1.0-4        Deriv_4.1.1          multcomp_1.4-14      bayestestR_0.7.5.1   expm_0.999-5        
[109] hms_0.5.3            rpart_4.1-15         grid_4.0.3           coda_0.19-4          class_7.3-17         minqa_1.2.4         
[115] rmarkdown_2.5        carData_3.0-4        base64enc_0.1-3      numDeriv_2016.8-1.1  lubridate_1.7.9      tinytex_0.26        `

**Comment by strengejacke** [comment]
Yes, I can reproduce this issue. Strange, as it worked for me yesterday...? I'll look into it, the problem here is `effectsize::standardize()`, which fails.

**Comment by mattansb** [comment]
Not sure exactly where this is happening (will have a look later), but I do have an easy fix - use `log1p(x)` instead of `log(x+1)`:

``` r
library(nlme)
library(effectsize)

reprex <- data.frame(
  time = as.factor(c(1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5)),
  group = c(1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2), 
  id = c(10, 10, 10, 10, 10, 15, 15, 15, 15, 15, 20, 20, 20, 20, 20, 25, 25, 25, 25, 25, 30, 30, 30, 30, 30, 35, 35, 35, 35, 35),
  sum = c(0, 5, 10, 15, 20, 0, 20, 25, 45, 50, 0, 5, 10, 15, 20, 0, 20, 25, 45, 50, 0, 5, 10, 15, 20, 0, 20, 25, 45, 50)
)

m1 <-  lme(
  log(sum + 1)  ~ as.numeric(time) * group,
  random  = ~ 1 | id,
  correlation = corAR1(form =  ~  as.numeric(time) | id),
  data = reprex,
  na.action = na.exclude
)

effectsize::effectsize(m1)
#> Warning in log(sum + 1): NaNs produced

#> Warning in log(sum + 1): NaNs produced
#> Error in MEEM(object, conLin, control$niterEM): NA/NaN/Inf in foreign function call (arg 1)


m2 <-  lme(
  log1p(sum)  ~ as.numeric(time) * group,
  random  = ~ 1 | id,
  correlation = corAR1(form =  ~  as.numeric(time) | id),
  data = reprex,
  na.action = na.exclude
)


effectsize::effectsize(m2)
#> Formula contains log- or sqrt-terms. See help("standardize") for how such terms are standardized.
#> Parameter              | Coefficient (std.) |        95% CI
#> -----------------------------------------------------------
#> (Intercept)            |               0.61 | [ 0.59, 0.64]
#> as.numeric(time)       |               0.17 | [ 0.16, 0.17]
#> group                  |               0.02 | [-0.02, 0.06]
#> as.numeric(time):group |               0.05 | [ 0.04, 0.06]
#> 
#> # Standardization method: Refit
```

<sup>Created on 2020-11-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
Yes, that would work. And I think a little tweak in the regex should fix this as well...

**Comment by strengejacke** [comment]
``` r
library(magrittr)
library(nlme)
library(report)
#> report is in alpha - help us improve by reporting bugs on github.com/easystats/report/issues
reprex <- data.frame(time = as.factor(c(1,2,3,4,5, 1, 2,3,4,5, 1, 2,3,4,5, 1, 2,3,4,5, 1, 2,3,4,5, 1, 2,3,4,5)), group=c(1,1,1,1,1, 2,2,2,2,2,1,1,1,1,1, 2,2,2,2,2,1,1,1,1,1, 2,2,2,2,2), id=c(10,10,10,10,10,15,15,15,15,15,20,20,20,20,20,25,25,25,25,25,30,30,30,30,30, 35,35,35,35,35), sum=c(0,5,10,15,20, 0,20,25,45,50,0,5,10,15,20, 0,20,25,45,50,0,5,10,15,20, 0,20,25,45,50))

m <-  lme(
  log(sum + 1)  ~ as.numeric(time) * group,
  random  = ~ 1 | id,
  correlation = corAR1(form =  ~  as.numeric(time) | id),
  data = reprex,
  na.action = na.exclude
)

report(m)
#> Formula contains log- or sqrt-terms. See help("standardize") for how such terms are standardized.
#> Formula contains log- or sqrt-terms. See help("standardize") for how such terms are standardized.
#> We fitted a linear mixed model (estimated using REML and nlminb optimizer) to predict sum with time, group and id (formula: log(sum + 1) ~ as.numeric(time) * group). The model included id as random effect (formula: ~1 | id). The model's total explanatory power is substantial (conditional R2 = 0.75) and the part related to the fixed effects alone (marginal R2) is of 0.75. The model's intercept, corresponding to time = 1 and group = 0, is at -0.46 (95% CI [-1.95, 1.03], t(22) = -0.64, p = 0.532). Within this model:
#> 
#>   - The effect of time is significantly positive (beta = 0.55, 95% CI [0.10, 1.01], t(22) = 2.51, p < .05; Std. beta = 0.17, 95% CI [0.16, 0.17])
#>   - The effect of group is non-significantly positive (beta = 0.46, 95% CI [-0.80, 1.72], t(22) = 1.02, p = 0.366; Std. beta = 0.02, 95% CI [-0.02, 0.06])
#>   - The interaction effect of group on time is non-significantly positive (beta = 0.13, 95% CI [-0.16, 0.42], t(4) = 0.94, p = 0.358; Std. beta = 0.05, 95% CI [0.04, 0.06])
#> 
#> Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using the Wald approximation.
```

<sup>Created on 2020-11-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Feathersjsextravagant** [comment]
Look at this https://stackdev.space/questions/when-utilizing-a-formula-within-an-r-function-an-object-not-found-error-may-be-produced conclusion
