### ISSUE TITLE
report() for t.test broken

### ISSUE THREAD

**Issue by McCartneyAC** [easystats/report#114]
So let's say I'm comparing the racial makeup of AP classes to the schools in which the classes takes place. Assuming for the sake of argument that these are normally distributed, I can do a paired sample t-test like this: 

```r
> # "AP Class"    
>   t.test(full_data$pctblack_apany , full_data$pctblack_enr,  paired = TRUE) %>% report()
Effect sizes were labelled following Cohen's (1988) recommendations.

The Paired t-test testing the difference between full_data$pctblack_apany and full_data$pctblack_enr (mean of 
the differences = -0.07) suggests that the effect is NA, significant and medium (difference = , 95% CI [-0.08, 
-0.06], t(300) = -11.96, p < .001; Cohen's d = -0.69, 95% CI [-0.82, -0.56])
```
Where `pctblack_apany` is the percent of students in any AP classes who are black, and `pctblack_enr` is the percent of students enrolled at the school who are black.

As you can see, instead of reporting " effect is negative, significant, and medium", I get an NA for the sign of the mean difference. This suggests to me that somewhere in the code is a calculation that needs `na.rm = T` and doesn't have it.

**Comment by DominiqueMakowski** [comment]
Hi, would you have a small reproducible code snippet so we investigate?

**Comment by McCartneyAC** [comment]
Sure! I took the top 20 observations of my data and can reproduce the error here: 

```r
  rep<-tibble::tribble(
    ~School,~pctblack_apany,~pctblack_enr,
    "Arcadia High",0.222,0.396,
    "Chincoteague High",0,0.14,
    "Nandua High",0.155,0.358,
    "Tangier Combined",0,0,
    "Albemarle High",0.0494,0.146,
    "Monticello High",0.0324,0.13,
    "Murray High",NA,0.0686,
    "Western Albemarle High",0.00402,0.0192,
    "T.C. Williams High",0.236,0.289,
    "Alleghany High",0,0.0816,
    "Altern Ed Prgm/Behav Disord Youth/Montgomery",NA,0.141,
    "Amelia County High",0.0857,0.234,
    "Amherst County High",0.173,0.235,
    "Appomattox County High",0.0857,0.239,
    "Appomattox Regional Governor's School",0.209,0.373,
    "Arlington Community High",NA,0.0655,
    "HB Woodlawn Secondary Program",0.0323,0.0351,
    "Langston High Continuation Program",NA,0.185,
    "New Directions Alternative H.S. Program",NA,0.303,
    "Technical Education & Career Center",NA,0.0864   
  )
report(t.test(rep$pctblack_apany , rep$pctblack_enr,  paired = TRUE))
#Effect sizes were labelled following Cohen's (1988) recommendations.

#The Paired t-test testing the difference between rep$pctblack_apany and rep$pctblack_enr (mean of the differences = -0.10) suggests that the effect is NA, significant and large (difference = , 95% CI [-0.14, -0.06], t(13) = -5.59, p < .001; Cohen's d = -1.55, 95% CI [-2.34, -0.73])
``` 


It also appears to me that in addition to the effect direction being NA, the `difference =  , 95% CI....` has an empty difference? Or is that supposed to be given as such?

**Comment by DominiqueMakowski** [comment]
``` r
report::report(t.test(mtcars$mpg, mtcars$vs, paired=TRUE))
#> Effect sizes were labelled following Cohen's (1988) recommendations.
#> 
#> The Paired t-test testing the difference between mtcars$mpg and mtcars$vs (mean of the differences = 19.65) suggests that the effect is NA, significant and large (difference = , 95% CI [17.60, 21.71], t(31) = 19.49, p < .001; Cohen's d = 3.50, 95% CI [2.56, 4.43])
```

<sup>Created on 2020-12-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Indeed, the issue is related to paired t tests. Let me see

**Comment by DominiqueMakowski** [comment]
Actually the error could be originating from `parameters`:

``` r
as.data.frame(parameters::model_parameters(t.test(mtcars$mpg, mtcars$vs, paired=TRUE)))
#>   Parameter1 Parameter2 Mean_Parameter1 Mean_Parameter2 Difference        t
#> 1 mtcars$mpg  mtcars$vs        19.65312              NA         NA 19.48822
#>   df_error            p   CI_low CI_high        Method
#> 1       31 5.939052e-19 17.59635 21.7099 Paired t-test
```

<sup>Created on 2020-12-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

We would need to adjust there (maybe in insight) to get the two mean groups if possible and the difference column

**Comment by strengejacke** [comment]
There were missing whitespace around `paired=TRUE`, now it works:

``` r
parameters::model_parameters(t.test(mtcars$mpg, mtcars$vs, paired = TRUE))
#> # Paired t-test
#> 
#> Parameter  |     Group | Difference | t(31) |      p |         95% CI
#> ---------------------------------------------------------------------
#> mtcars$mpg | mtcars$vs |      19.65 | 19.49 | < .001 | [17.60, 21.71]
```

<sup>Created on 2021-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
Re-opening, because due to the latest changed, `report()` for `t.test()` no longer works, at least not for paired t-tests:

``` r
report::report(t.test(mtcars$mpg, mtcars$vs, paired = TRUE))
#> Warning: 'y' is numeric but has only 2 unique values. If this is a grouping
#> variable, convert it to a factor.
#> Error in `[.data.frame`(table, c("d", "d_CI_low", "d_CI_high")): undefined columns selected
```

<sup>Created on 2021-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
``` r
report::report(t.test(mtcars$mpg, mtcars$vs, paired = TRUE), verbose = FALSE)
#> Warning: 'y' is numeric but has only 2 unique values. If this is a grouping
#> variable, convert it to a factor.
#> Effect sizes were labelled following Cohen's (1988) recommendations.
#> 
#> The Paired t-test testing the difference between mtcars$mpg and mtcars$vs (mean of the differences = 19.65) suggests that the effect is positive, significant and large (difference = 19.65, 95% CI [17.60, 21.71], t(31) = 19.49, p < .001; Cohen's d = 3.45, 95% CI [2.56, 4.43])
```

<sup>Created on 2021-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

@mattansb @DominiqueMakowski Not sure why the warning is still yielded, even when setting `verbose = FALSE` - any ideas?

**Comment by mattansb** [comment]
fixed

``` r
effectsize::effectsize(t.test(mtcars$mpg, mtcars$vs, paired = TRUE), verbose = FALSE)
#> Cohen's d |       95% CI
#> ------------------------
#> 3.45      | [2.56, 4.43]
```

<sup>Created on 2021-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mscharkow** [comment]
Using the latest versions, the error is still there if you use formula notation for the same t-test:

`r report::report(t.test(mpg~vs, mtcars))`

Error in `[.data.frame`(table, c("Cohens_d", "d_CI_low", "d_CI_high")) : 
  undefined columns selected
Zusätzlich: Warnmeldung:
In effectsize.htest(x, ...) :
  Unable to retrieve data from htest object. Using t_to_d() approximation.

**Comment by mattansb** [comment]
@DominiqueMakowski `insight::get_data.htest()` doesn't always work. When this happens, `effectsize.htest()` for t tests gives an approximation labeled "d" (not "cohen's d" exactly).
