### ISSUE TITLE
cran update

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/report#214]
Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_report.html>.

Please correct before 2022-01-31 to safely retain your package on CRAN.

**Comment by strengejacke** [comment]
Looks like you just have to replace `effectsize::interpret_d()` with the new function. @mattansb ?

**Comment by mattansb** [comment]
This is already done on Github - just need to submit to CRAN (:

**Comment by IndrajeetPatil** [comment]
Once https://github.com/easystats/report/issues/203 is resolved, we are ready for submission.

**Comment by IndrajeetPatil** [comment]
@DominiqueMakowski We are ready for submission. We can deal with #221 later. I think it would work out of the box once `{effectsize}` is updated on CRAN.

**Comment by DominiqueMakowski** [comment]
Should we comment-off / dontrun the example:

```
E  checking examples (25.7s)
   Running examples in 'report-Ex.R' failed
   The error most likely occurred in:
   
   > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
   > ### Name: report_performance
   > ### Title: Report the model's quality and fit indices
   > ### Aliases: report_performance
   > 
   > ### ** Examples
   > 
   > ## No test: 
   > library(report)
   > 
   > # GLMs
   > report_performance(lm(Sepal.Length ~ Petal.Length * Species, data = iris))
   The model explains a statistically significant and substantial proportion of variance (R2 = 0.84, F(5, 144) = 151.71, p < .001, adj. R2 = 0.83)> report_performance(glm(vs ~ disp, data = mtcars, family = "binomial"))
   The model's explanatory power is substantial (Tjur's R2 = 0.53)> 
   > # Mixed models
   > if (require("lme4")) {
   +   model <- lme4::lmer(Sepal.Length ~ Petal.Length + (1 | Species), data = iris)
   +   report_performance(model)
   + }
   Loading required package: lme4
   Loading required package: Matrix
   The model's total explanatory power is substantial (conditional R2 = 0.97) and the part related to the fixed effects alone (marginal R2) is of 0.66> 
   > # Bayesian models
   > if (require("rstanarm")) {
   +   model <- stan_glm(Sepal.Length ~ Species, data = iris, refresh = 0, iter = 600)
   +   report_performance(model)
   + }
   Loading required package: rstanarm
   Loading required package: Rcpp
   This is rstanarm version 2.21.1
   - See https://mc-stan.org/rstanarm/articles/priors for changes to default priors!
   - Default priors may change, so it's safest to specify priors, even if equivalent to the defaults.
   - For execution on a local, multicore CPU with excess RAM we recommend calling
     options(mc.cores = parallel::detectCores())
   The model's explanatory power is substantial (R2 = 0.61, 95% CI [0.53, 0.69], adj. R2 = 0.61)> 
   > # Structural Equation Models (SEM)
   > if (require("lavaan") && packageVersion("effectsize") >= "0.6.0.1") {
   +   structure <- " ind60 =~ x1 + x2 + x3
   +                  dem60 =~ y1 + y2 + y3
   +                  dem60 ~ ind60 "
   +   model <- lavaan::sem(structure, data = PoliticalDemocracy)
   +   report_performance(model)
   + }
   Loading required package: lavaan
   This is lavaan 0.6-9
   lavaan is FREE software! Please report any bugs.
   Error in UseMethod("format_value") : 
     no applicable method for 'format_value' applied to an object of class "NULL"
   Calls: report_performance ... .text_performance_lavaan -> paste0 -> substring -> <Anonymous>
   Execution halted
```

I still have that:

```
== Warnings ====================================================================
-- Warning (test-report.aov.R:26:3): report.aov --------------------------------
Some CIs could not be estimated due to non-finite F, df, or df_error values.
Backtrace:
  1. report::report(model) test-report.aov.R:26:2
  2. report:::report.aovlist(model)
  4. report:::report_table.aovlist(x, ...)
  6. report:::report_effectsize.aovlist(x, ...)
  8. effectsize:::effectsize.aovlist(x, ...)
  9. effectsize:::f(model, ...)
 11. effectsize:::.anova_es.aovlist(...)
 12. effectsize::.es_aov_strata(...)
 13. effectsize::F_to_eta2(...)
 14. effectsize:::.F_to_pve(...)
-- Warning (test-report.htest-correlation.R:7:3): report.htest-correlation -----
Cannot compute exact p-value with ties
Backtrace:
 1. report::report(...) test-report.htest-correlation.R:7:2
 3. stats:::cor.test.default(...)
-- Warning (test-report.stanreg.R:3:3): (code run outside of `test_that()`) ----
Bulk Effective Samples Size (ESS) is too low, indicating posterior means and medians may be unreliable.
Running the chains for more iterations may help. See
http://mc-stan.org/misc/warnings.html#bulk-ess
Backtrace:
 1. rstanarm::stan_glm(...) test-report.stanreg.R:3:2
 2. rstanarm::stan_glm.fit(...)
 6. rstan:::.local(object, ...)
 7. rstan:::throw_sampler_warnings(nfit)
-- Warning (test-report.stanreg.R:3:3): (code run outside of `test_that()`) ----
Tail Effective Samples Size (ESS) is too low, indicating posterior variances and tail quantiles may be unreliable.
Running the chains for more iterations may help. See
http://mc-stan.org/misc/warnings.html#tail-ess
Backtrace:
 1. rstanarm::stan_glm(...) test-report.stanreg.R:3:2
 2. rstanarm::stan_glm.fit(...)
 6. rstan:::.local(object, ...)
 7. rstan:::throw_sampler_warnings(nfit)

== Failed tests ================================================================
-- Error (test-report.aov.R:33:3): report.aov ----------------------------------
Error: unused argument (variant = .Platform$OS.type)
-- Error (test-report.data.frame.R:38:3): report.factor ------------------------
Error: unused argument (variant = .Platform$OS.type)
-- Error (test-report.data.frame.R:65:5): report.data.frame --------------------
Error: unused argument (variant = .Platform$OS.type)
-- Error (test-report.data.frame.R:74:5): report.data.frame - with NAs ---------
Error: unused argument (variant = .Platform$OS.type)
-- Error (test-report.htest-correlation.R:16:3): report.htest-correlation ------
Error: unused argument (variant = .Platform$OS.type)
-- Error (test-report.htest-t-test.R:27:3): report.htest-t-test ----------------
Error: unused argument (variant = .Platform$OS.type)
-- Error (test-report.ivreg.R:13:5): report-survreg ----------------------------
Error: unused argument (variant = .Platform$OS.type)
-- Error (test-report.lavaan.R:13:5): model-lavaan detailed report -------------
Error: unused argument (variant = .Platform$OS.type)
-- Error (test-report.lavaan.R:17:5): model-lavaan detailed table --------------
Error: unused argument (variant = .Platform$OS.type)
-- Error (test-report.lm.R:6:3): report.lm - lm --------------------------------
Error: unused argument (variant = .Platform$OS.type)
-- Error (test-report.lm.R:17:3): report.lm - glm ------------------------------
Error: unused argument (variant = .Platform$OS.type)
-- Error (test-report.lmer.R:19:5): report-lmer --------------------------------
Error: unused argument (variant = .Platform$OS.type)
-- Error (test-report.stanreg.R:34:5): model-stanreg detailed ------------------
Error: unused argument (variant = .Platform$OS.type)
-- Error (test-report.survreg.R:13:5): report-survreg --------------------------
Error: unused argument (variant = .Platform$OS.type)

[ FAIL 14 | WARN 4 | SKIP 0 | PASS 113 ]
Deleting unused snapshots:
* _snaps/windows
Error: Test failures
Execution halted

2 errors x | 1 warning x | 0 notes v
Error: R CMD check found ERRORs
```

anyone knows what are the OSplatform things ?

**Comment by IndrajeetPatil** [comment]
> Should we comment-off / dontrun the example:

Yepp.

> anyone knows what are the OSplatform things ?

Are you using an old version of `testthat`? At any rate, the snapshot tests are not run on CRAN, so these won't cause trouble during the submission process.

Snapshot tests are quite brittle, so I had saved snapshot variants only for Windows.

![image](https://user-images.githubusercontent.com/11330453/151684713-492a70f1-d1aa-46cd-af56-5a530346c68c.png)

**Comment by DominiqueMakowski** [comment]
I updated testthat and now everything works, aside from this last thing:

```
W  checking re-building of vignette outputs (3.2s)
   Error(s) in re-building vignettes:
   --- re-building 'cite_packages.Rmd' using rmarkdown
   
   Attaching package: 'dplyr'
   
   The following objects are masked from 'package:stats':
   
       filter, lag
   
   The following objects are masked from 'package:base':
   
       intersect, setdiff, setequal, union
   
   --- finished re-building 'cite_packages.Rmd'
   
   --- re-building 'new_models.Rmd' using rmarkdown
   --- finished re-building 'new_models.Rmd'
   
   --- re-building 'report.Rmd' using rmarkdown
   Warning in file(con, "w") :
     cannot open file 'C:\Dropbox\RECHERCHE\N\easystats\report.Rcheck\vign_test\report\vignettes\report.R': Invalid argument
   Quitting from lines 44-46 (report.Rmd) 
   Error: processing vignette 'report.Rmd' failed with diagnostics:
   cannot open the connection
   --- failed re-building 'report.Rmd'
   
   SUMMARY: processing the following file failed:
     'report.Rmd'
   
   Error: Vignette re-building failed.
   Execution halted
```

I checked the vignette manually but couldn't find any issue 🤔

**Comment by IndrajeetPatil** [comment]
> --- failed re-building 'report.Rmd'

This should be fixed now.

**Comment by DominiqueMakowski** [comment]
Winbuilds pass without problems though, so I'll just submit :)

**Comment by DominiqueMakowski** [comment]
On its way to cran

**Comment by IndrajeetPatil** [comment]
That was fast! 😮

Thank you, CRAN 🙇‍♂️

**Comment by IndrajeetPatil** [comment]
Dom, did this update actually ever make it to CRAN? Do you have an email about that? It is possible that it never made it to CRAN and that's why the package got archived.

The [archive ](https://cran.r-project.org/src/contrib/Archive/report/) shows that the release before archival is from April 2021, and not January 2022, as it should be if this update made to CRAN:

![image](https://user-images.githubusercontent.com/11330453/155168586-491225e2-8dce-4e0d-b600-d8156ab408ca.png)
