### ISSUE TITLE
Error: 'format_value' is not an exported object from 'namespace:parameters'

### ISSUE THREAD

**Issue by diodon** [easystats/report#46]
Recently install the package and it fails producing the report of a data frame:

> library(report)
> report(iris)
> Error: 'format_value' is not an exported object from 'namespace:parameters'

The same error trying to produce the report with `mtcars`

However, it works well with 

> lm(Sepal.Length ~ Petal.Length + Species, data=iris) %>% 
> report() %>% 
> to_table()

The error popup in a fresh session of R 3.6.1 with the `report` version 0.1.0

**Comment by DominiqueMakowski** [comment]
We recently moved `format_value` from parameters to `insight`:

Could you please run:

```r
devtools::install_github("easystats/insight")
devtools::install_github("easystats/parameters")
devtools::install_github("easystats/report")
```
And them try again? Thanks!

**Comment by diodon** [comment]
I've installed the above mentioned packages but the error persists:

`Error: 'format_value' is not an exported object from 'namespace:parameters'`

**Comment by strengejacke** [comment]
Have you installed all the three packages from _GitHub_?

**Comment by diodon** [comment]
yes I did. I even forced the installation of all packages again. Same error:

```
> devtools::install_github("easystats/report", force=T)
Downloading GitHub repo easystats/report@master
from URL https://api.github.com/repos/easystats/report/zipball/master
Installing report
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpIAjqCG/devtools18d875d01710/easystats-report-c61a6c6' --library='/home/eklein/R/x86_64-pc-linux-gnu-library/3.6'  \
  --install-tests 

* installing *source* package ‘report’ ...
** using staged installation
** R
** inst
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (report)
> library(report)
> report(iris)
Error: 'format_value' is not an exported object from 'namespace:parameters'
```

**Comment by DominiqueMakowski** [comment]
Hi @diodon, could you try running this first:

```r
devtools::install_github(c("easystats/insight",
                             "easystats/bayestestR",
                             "easystats/performance",
                             "easystats/parameters",
                             "easystats/correlation",
                             "easystats/estimate",
                             "easystats/see",
                             "easystats/report"))
```

**Comment by diodon** [comment]
done, but sorry, the error persists...

**Comment by DominiqueMakowski** [comment]
🤔 🤔  That's very weird. So sorry about that, but could you try with:

```
devtools::install_github(c("easystats/insight",
                             "easystats/bayestestR",
                             "easystats/performance",
                             "easystats/parameters",
                             "easystats/correlation",
                             "easystats/estimate",
                             "easystats/see",
                             "easystats/report"), 
                                   force = TRUE)
```

**Comment by DominiqueMakowski** [comment]
@diodon I think I know why it might not work... It should be fixed now. Could you try again reinstalling `report` from github (so sorry for these reinstallations ☺️)

**Comment by mfox9** [comment]
Hello, I'm having the same issue and tried all of the above suggestions. Still receiving the same error message.

**Comment by DominiqueMakowski** [comment]
Hi @mfox9 

I am super sorry but report is currently broken again due to recent major changes in the other easystats packages. Will be fixed soon! Please hang on and apologies for the inconvenience!!

In the meantime, note that you can obtain all the information that `report` gives as tables using `model_parameters()` (in the parameters package) and `model_performance()` (in the performance package). Let us know if you need anything!

**Comment by strengejacke** [comment]
After updating _insight_ and _parameters_ from CRAN, and _report_ from GitHub (master), this should now work.

**Comment by rkofreitag** [comment]
Hi, I'm trying to install `report`, but the following error messages is shown:

Failed to install 'report' from GitHub:
 Failed to install 'insight' from GitHub:
 lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/pkgbuild/R/pkgbuild.rdb' is corrupt

It is a trouble in my computer?

Thank you!

**Comment by DominiqueMakowski** [comment]
Could be similar to https://github.com/lme4/lme4/issues/407 Have you tried restarting R?

**Comment by strengejacke** [comment]
Looks like you should remove and reinstall the pkgbuild package?

**Comment by rkofreitag** [comment]
Sorry... so simple restart R... it's working perfectly now, thank you!
