### ISSUE TITLE
Having some trouble runnign report with lm

### ISSUE THREAD

**Issue by cesterwo1056** [easystats/report#56]
I'm utilizing R studio and trying to run "report" on the following code to summarize the output in plain text. 

`lm.out <- lm(time ~ year, data=Q2_Data)`

`report(lm.out)`

Utilizing this, I then see the following error:

`Error in UseMethod("format_value") : 
  no applicable method for 'format_value' applied to an object of class "NULL"`

The data I'm utilizing this for is open source as I am experimenting with this package and I've attached it here for reference. 

[olympics copy.sav.zip](https://github.com/easystats/report/files/3923343/olympics.copy.sav.zip)

Let me know if there is something I'm doing wrong here.  I'm fairly new to the R world so it could be entirely on my side but I thought if anyone would know it would be you guys :)

**Comment by gorkang** [comment]
The same error appears when running the example shown in the README:

```
lm(Sepal.Length ~ Petal.Length + Species, data=iris) %>%
  report() %>%
  to_table() 
```

> Error in UseMethod("format_value") : 
>   no applicable method for 'format_value' applied to an object of class "NULL"

**Comment by Paul-Yuchao-Dong** [comment]
Same result here running the glm. I was prompted to install effectsize package first. But this problem persisted after restarting R and RStudio.

``` r
library(tidyverse)
library(report)

model <- glm(vs ~ mpg + cyl, data = mtcars, family = "binomial") 
report(model)
#> Waiting for profiling to be done...
#> Error in UseMethod("format_value"): no applicable method for 'format_value' applied to an object of class "NULL"

```

<sup>Created on 2020-01-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by sedufau** [comment]
Solved it by by installing _parameters_ and loading it (https://github.com/easystats/parameters)
`install.packages("parameters")` 
`# easystats libraries` 
`library(parameters)`
`library(report)`

**Comment by glennalthor** [comment]
I'm also getting this error, installing parameters didn't help. 

My code:

glm1 <- glm(any_vis ~ q2 + q3 + q4 + q5 + q6 + q7, 
           family="binomial",
           data = dat)
summary(glm1)
report(glm1)

Error: Waiting for profiling to be done...
Error in UseMethod("format_value") : 
  no applicable method for 'format_value' applied to an object of class "NULL"

**Comment by glennalthor** [comment]
I was able to resolve this by installing the entire easystats suite.

**Comment by Paul-Yuchao-Dong** [comment]
I was able to resolve this by installing the entire easystats suite as well. the sequence I used was to install the suite then install report, and it worked.

**Comment by strengejacke** [comment]
Sorry for the inconvenience, but this is simply due to the "project planning" and the order of package development (see, e.g., this presentation: https://github.com/easystats/easystats/blob/master/presentations/ludecke_2019_02_Hamburg_RUG/1902%20Hamburg%20RUG%20easystats.pdf).

We started by developing the low-level packages and then build up our easystats-suite by focussing on packages on the next level and so on. Thus, as some packages are still not fixed in their api and function design etc. is changing, the "higher level" packages like report, which are not yet on CRAN, will probably cause troubles every now and then.

For instance, some functions that used to be in the _parameters_ package, were now re-implemented in the _effectsize_ package. This had a strong impact on _report_ (see https://github.com/easystats/report/pull/50).

Maybe we can have a more or less stable working version by the mid of this year, but I don't want to promise any deadline here.

**Comment by Paul-Yuchao-Dong** [comment]
@strengejacke thank you and your team for this great package. I personally like report the most because it interprets the r outputs into human language, compare and contrast that with the output of summary, it helped one learn stats rather quickly. 

Though my programming ability is rather limited, I still like to try to help you to make report work better with the lower level package. Let me take a look at the issue list and contribution guidelines.

**Comment by glennalthor** [comment]
No need for apologies, you have done an amazing job with this wonderful series of packages!!! Report in particular is simply amazing.

**Comment by DominiqueMakowski** [comment]
the good news is that now the focus will shift back to report as all the other necessary "ingredients" are getting ready and stable :man_cook: 

Also, I should now finally have some time to fix the existing functionalities of this package in the next few days :relaxed:

 stay tuned and thanks for your support and patience!

**Comment by strengejacke** [comment]
Should be fixed now (at current master branch), if you use `table_long()` or `table_short()`.

``` r
library(report)
library(magrittr)
data(iris)

lm(Sepal.Length ~ Petal.Length + Species, data=iris) %>%
  report() %>%
  table_long() 
#> Parameter         | Coefficient |   SE | CI_low | CI_high |     t | df_error |    p | Std_Coefficient |    Fit
#> --------------------------------------------------------------------------------------------------------------
#> (Intercept)       |        1.50 | 0.19 |   1.12 |    1.87 |  7.93 |      146 | 0.00 |            1.50 |       
#> Petal.Length      |        1.93 | 0.14 |   1.66 |    2.20 | 13.96 |      146 | 0.00 |            1.93 |       
#> Speciesversicolor |       -1.93 | 0.23 |  -2.40 |   -1.47 | -8.28 |      146 | 0.00 |           -1.93 |       
#> Speciesvirginica  |       -2.56 | 0.33 |  -3.21 |   -1.90 | -7.74 |      146 | 0.00 |           -2.56 |       
#>                   |             |      |        |         |       |          |      |                 |       
#> AIC               |             |      |        |         |       |          |      |                 | 106.23
#> BIC               |             |      |        |         |       |          |      |                 | 121.29
#> R2                |             |      |        |         |       |          |      |                 |   0.84
#> R2 (adj.)         |             |      |        |         |       |          |      |                 |   0.83
#> RMSE              |             |      |        |         |       |          |      |                 |   0.33

lm(Sepal.Length ~ Petal.Length + Species, data=iris) %>%
  report() %>%
  table_short() 
#> Parameter         | Coefficient | CI_low | CI_high |    p | Std_Coefficient |  Fit
#> ----------------------------------------------------------------------------------
#> (Intercept)       |        1.50 |   1.12 |    1.87 | 0.00 |            1.50 |     
#> Petal.Length      |        1.93 |   1.66 |    2.20 | 0.00 |            1.93 |     
#> Speciesversicolor |       -1.93 |  -2.40 |   -1.47 | 0.00 |           -1.93 |     
#> Speciesvirginica  |       -2.56 |  -3.21 |   -1.90 | 0.00 |           -2.56 |     
#>                   |             |        |         |      |                 |     
#> R2                |             |        |         |      |                 | 0.84
#> R2 (adj.)         |             |        |         |      |                 | 0.83
```

<sup>Created on 2020-02-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
oh, and ofcourse `report()` only:

``` r
lm(Sepal.Length ~ Petal.Length + Species, data=iris) %>%
  report()
#> We fitted a linear model (estimated using OLS) to predict Sepal.Length with Petal.Length and Species (formula = Sepal.Length ~ Petal.Length + Species). Standardized parameters were obtained by fitting the model on a standardized version of the dataset. Effect sizes were labelled following Funder's (2019) recommendations.
#> 
#> The model explains a significant and substantial proportion of variance (R2 = 0.84, F(3, 146) = 249.40, p < .001, adj. R2 = 0.83). The model's intercept, corresponding to Sepal.Length = 0, Petal.Length = 0 and Species = setosa, is at 3.68 (SE = 0.11, 95% CI [3.47, 3.89], p < .001). Within this model:
#> 
#>   - The effect of Petal.Length is positive and can be considered as very large and significant (beta = 1.93, SE = 0.14, 95% CI [1.66, 2.20], std. beta = 1.93, p < .001).
#>   - The effect of Speciesversicolor is negative and can be considered as very large and significant (beta = -1.93, SE = 0.23, 95% CI [-2.40, -1.47], std. beta = -1.93, p < .001).
#>   - The effect of Speciesvirginica is negative and can be considered as very large and significant (beta = -2.56, SE = 0.33, 95% CI [-3.21, -1.90], std. beta = -2.56, p < .001).
```

**Comment by zen-juen** [comment]
Hi there,
It seems like I'm encountering similar `report()` issues as were mentioned previously in this issue.
```
report_participants(df_final, sex="Gender")

#Error in UseMethod("format_value") : 
 no applicable method for 'format_value' applied to an object of class "NULL"
```
I've tried re-installing `report()` and with `report(iris)` but am still encountering the same problems, will appreciate any help I can get!  :)

**Comment by sielerjm** [comment]
I'm also encountering a similar problem. I installed easystats collection after installing report individually. I tried reinstalling report separately, but no luck so far.

**Comment by bwiernik** [comment]
Please move further discussion to the new issue. This is a different problem
